sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
cache:
  directories:
  - node_modules
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
