sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
